# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

start = Time.now
seq = [1,1]

loop do
	seq[-1] > 4000000 ? break : seq << seq[-1] + seq[-2]
end

p seq.select{ |n| n % 2 == 0 }.reduce(:+)
p Time.now - start

# 4613732
# 3.7e-05 seconds