# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:

# Triangle	 	T_n = n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	P_n = n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	H_n = n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

start = Time.now

# All Hexagonal numbers are triangular; so triangularity is superfluous.

def is_pent?(k)
# 3 * n**2 - n - 2k = 0 where n is an integer
# 1 +- sqrt(1 - 4*3*(-2k)) / 6
# 1 + 24*k must be a perfect square and 1 + sqrt(24*k) % 6 == 0
	(Math.sqrt(1 + 24*k).to_i)**2 == 1 + 24*k &&
	(1 + Math.sqrt(1 + 24*k)) % 6 == 0
end

def h(n); n * (2*n -1) end

n = 143
loop do
	n += 1
	if is_pent?(h(n))
		p h(n)
		break
	end
end

p Time.now - start

# 1533776805
# 0.015366 seconds
